---
# https://www.elastic.co/guide/en/logstash/current/package-repositories.html

# Download and install the Public Signing Key
- apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

# Add the repository definition to your /etc/apt/sources.list file
- name: Add repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/2.0/debian stable main"
  args:
    state: present
    update_cache: yes

- name: Install
  apt: name=logstash
  args:
    state: present
    force: yes
